version: '3.8'

services:
  gitback:
    build:
      context: .
      dockerfile: Dockerfile
    image: gitback:local
    container_name: gitback
    environment:
      - GITBACK_TOKEN=${GITHUB_TOKEN}
      - GITBACK_USER=${GITHUB_USER}
      - GITBACK_OUTPUT_DIR=/data
      - GITBACK_THREADS=5
      - GITBACK_TIMEOUT=30
      - GITBACK_INCLUDE_GISTS=true
    volumes:
      - ./data:/data
    restart: unless-stopped
    # Uncomment the following lines to run a specific command
    # command: ["--help"]
    # entrypoint: ["/app/gitback"]

  # Uncomment this section to add a simple web server to view the backed-up files
  # web:
  #   image: nginx:alpine
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./data:/usr/share/nginx/html:ro
  #   depends_on:
  #     - gitback
  #   restart: unless-stopped
